import type { GuidedContent, SourceExcerpt } from './guidedTypes'

const word = (source: string, iast: string, meaning: string, grammar: string) => ({ source, iast, meaning, grammar })
const excerpt = (reference: string, devanagari: string, iast: string, translation: string, sourceUrl: string, note: string, words: SourceExcerpt['words']): SourceExcerpt => ({ reference, devanagari, iast, translation, sourceUrl, note, words })
const portal = (name: string) => `https://vedicheritage.gov.in/upanishads/${name}/`

export const upanishadGuides: Record<string, GuidedContent> = {
  mundaka: {
    opening: 'You can know a library by heart and still not know what your life is for. Śaunaka’s question is more ambitious than “What else should I study?” He asks what knowledge would illuminate everything else.',
    teaching: [
      { title: 'A question about the ground, not all the facts', body: 'In 1.1.3, the householder Śaunaka approaches Aṅgiras. His question does not promise that a student will suddenly know every language or number. It asks for the underlying reality on which many kinds of knowledge depend. Notice the learner’s respectful approach: inquiry happens within a relationship, not through a detached slogan.' },
      { title: 'Two kinds of learning, two different aims', body: 'Verses 1.1.4–5 include the four Vedas, pronunciation, ritual, grammar, etymology, meter, and calendrics under aparā learning. That surprising classification is made within a Vedic work. Parā learning is distinguished by knowing the imperishable. The test is what the knowledge reaches, not whether its vocabulary sounds spiritual.' },
      { title: 'Two birds make the distinction visible', body: 'In 3.1.1–2, one bird eats the tree’s fruit while its companion watches. The troubled bird sees the other’s greatness and becomes free of sorrow. Keep the roles distinct before deciding their ultimate relationship. Nondual and theistic readers develop different answers; the image alone is not a complete later Vedānta system.' },
    ],
    example: { title: 'Knowing about patience', scenario: 'Modern illustration: a student can define patience perfectly but reacts angrily to every delay. Another notices the reaction and responds more steadily. How does this help explain the difference between possessing information and being changed by understanding?', explanation: 'The contrast makes transformative knowledge intelligible, but it is only an analogy. Muṇḍaka’s specific object is the imperishable, not improved emotional skills. Recognizing that limit keeps an everyday example from replacing the text’s own claim.' },
    visual: { title: 'One tree, two relationships to its fruit', nodes: [{ label: 'The tree', detail: 'The shared setting of lived experience. The birds are not in separate universes.' }, { label: 'Eating bird', detail: 'Participation, enjoyment, and sorrow: being caught up in what happens.' }, { label: 'Watching companion', detail: 'A different relation to experience becomes visible. Interpreters disagree about identity or difference between the birds.' }], caption: 'A reading aid for 3.1.1–2, not a diagram of two anatomical selves.' },
    connections: [{ lessonId: 'vedangas-sutras', why: 'Meet the disciplines that Muṇḍaka explicitly includes in aparā learning.' }, { lessonId: 'kena', why: 'Compare knowing an object with questioning what makes knowing possible.' }],
    sourceLinks: [{ label: 'Sanskrit: Muṇḍaka, Vedic Heritage Portal', url: portal('mundakopanishad') }, { label: 'Muṇḍaka 1.1, Müller’s historical translation', url: 'https://sacred-texts.com/hin/sbe15/sbe15016.htm' }],
    excerpt: excerpt('Muṇḍaka 1.1.5 · concluding sentence', 'अथ परा यया तदक्षरमधिगम्यते ।', 'atha parā yayā tad akṣaram adhigamyate', 'Now, the higher [knowledge] is that through which that imperishable is apprehended.', portal('mundakopanishad'), 'This is the end of 1.1.5, not the full verse. Vidyā, “knowledge,” is understood with parā. The source joins tad + akṣaram and akṣaram + adhigamyate; the learning rows separate them.', [word('अथ', 'atha', 'now; next', 'Indeclinable transition.'), word('परा', 'parā', 'higher [knowledge]', 'Feminine nominative singular; vidyā is understood.'), word('यया', 'yayā', 'through which', 'Instrumental feminine singular of the relative pronoun.'), word('तत्', 'tat', 'that', 'Neuter singular pronoun qualifying akṣaram; final t voices before the vowel.'), word('अक्षरम्', 'akṣaram', 'imperishable', 'Neuter nominative singular; subject of the passive verb.'), word('अधिगम्यते', 'adhigamyate', 'is apprehended; is reached', 'Third-person singular present passive of adhi-√gam.')]),
  },
  taittiriya: {
    opening: 'What would graduation mean if your teacher cared as much about how you lived as how accurately you could recite? This Upaniṣad begins with disciplined learning and keeps returning to the conditions that sustain a person.',
    teaching: [
      { title: 'Education has an afterlife in conduct', body: 'Śikṣāvallī 1.11 addresses a departing student: truthfulness, responsibility, continuing study, teachers, guests, and thoughtful giving belong together. These are not optional decorations around the “real” philosophy. The teaching asks whether knowledge will survive contact with ordinary obligations after formal study ends.' },
      { title: 'Move inward without discarding the body', body: 'The second vallī moves through persons described in terms of food, breath, mind, understanding, and bliss. Each account opens toward another. Begin with dependence: a thinking person is also sustained by food and vital functioning. The familiar five-sheath diagram is a later interpretive organization of this sequence, not a literal anatomical illustration printed in the text.' },
      { title: 'Bhṛgu learns by returning to his question', body: 'In the third vallī, Bhṛgu asks Varuṇa about brahman and is directed toward sustained inquiry. He successively examines food, vital life, mind, understanding, and bliss. The repeated return matters: the first plausible answer is tested and deepened. The ending’s concern for food and hospitality prevents inward inquiry from simply abandoning embodied life.' },
    ],
    example: { title: 'A brilliant but irresponsible graduate', scenario: 'Modern illustration: a graduate explains difficult ideas eloquently but falsifies evidence and treats visitors dismissively. Which part of the education described in 1.11 has not taken hold?', explanation: 'Technical accomplishment has been separated from truthfulness and responsibility. The passage challenges that separation. You need not endorse every ancient social expectation to recognize that the text treats conduct and continued learning as part of education itself.' },
    visual: { title: 'Three movements of an education', nodes: [{ label: 'Learn and live', detail: 'Śikṣāvallī: disciplined speech, study, and responsibilities.' }, { label: 'Examine the person', detail: 'Brahmānandavallī: food, vitality, thought, understanding, and bliss.' }, { label: 'Return and inquire', detail: 'Bhṛguvallī: repeated investigation, ending with sustaining and welcoming life.' }], caption: 'The three vallīs are complementary movements; this is not a five-layer physical body chart.' },
    connections: [{ lessonId: 'paninian-grammar', why: 'See another tradition in which disciplined language and teaching are central.' }, { lessonId: 'isha', why: 'Compare the relation between insight and responsible action.' }],
    sourceLinks: [{ label: 'Taittirīya Sanskrit with accents', url: 'https://sanskritdocuments.org/doc_upanishhat/taitaccent.html' }, { label: 'Vedic Heritage: Taittirīya Āraṇyaka', url: 'https://vedicheritage.gov.in/aranyakas/taittiriya-aranyaka/' }],
    excerpt: excerpt('Taittirīya 1.11.1 · two instructions', 'सत्यं वद । धर्मं चर ।', 'satyaṃ vada | dharmaṃ cara', 'Speak truth. Practice what is right.', 'https://sanskritdocuments.org/doc_upanishhat/taitaccent.html', 'A short excerpt from a much longer farewell instruction; Vedic accent marks are omitted for beginning readers. Dharma here names responsible conduct, not a context-free modern legal code.', [word('सत्यम्', 'satyam', 'truth', 'Accusative neuter singular, object of vada; final m appears as ṃ before v.'), word('वद', 'vada', 'speak', 'Second-person singular imperative of √vad.'), word('धर्मम्', 'dharmam', 'right conduct; duty', 'Accusative masculine singular, object of cara; final m becomes ṃ before c.'), word('चर', 'cara', 'practice; live by', 'Second-person singular imperative of √car, literally move or conduct oneself.')]),
  },
  chandogya: {
    opening: 'Śvetaketu returns from study proud of what he knows. His father asks whether he learned how the many relate to their underlying reality. The lesson proceeds through ordinary materials: clay, a seed, and salt in water.',
    teaching: [
      { title: 'A big book, not a single saying', body: 'Chāndogya has eight chapters of chant interpretation, cosmology, teaching encounters, and inquiry into self. Chapter 6 is one influential strand. Reading its repeated refrain without its experiments misses Uddālaka’s method: he moves Śvetaketu from familiar examples toward something the learner cannot simply point to.' },
      { title: 'What clay can teach', body: 'At 6.1, knowing clay illuminates clay objects despite their different names and shapes. This establishes a question about material ground and transformation. It does not say that a bowl and a jar have identical everyday uses. Distinguish what is shared from the differences the example leaves intact.' },
      { title: 'From the unseen to the learner', body: 'In 6.12–13, the subtle interior of a seed and salt dissolved in water support reflection on what is present without being separately visible. The refrain tat tvam asi connects Śvetaketu to that subtle reality. Later readers debate precisely how; the examples prepare an inquiry, not an excuse to claim that any invisible thing must exist.' },
    ],
    example: { title: 'The salt lesson', scenario: 'Textual example, Chāndogya 6.13: salt is left in water. Śvetaketu cannot retrieve it as a visible lump, yet water tasted at different places is salty. What has the demonstration established, and what has it not yet established?', explanation: 'It establishes that something may be present without being separately visible, using taste as evidence. The wider claim about self and being is the philosophical teaching for which this is an analogy; the salt experiment alone does not prove an entire metaphysical system.' },
    visual: { title: 'Follow the analogy without skipping its steps', nodes: [{ label: 'Visible lump', detail: 'Salt begins as a separately identifiable object.' }, { label: 'Dissolved presence', detail: 'Its absence from sight is tested by a different mode: taste.' }, { label: 'Philosophical extension', detail: 'Uddālaka uses the example to teach subtle presence, then addresses Śvetaketu himself.' }], caption: 'An argument map for the teaching, not a laboratory proof of brahman.' },
    connections: [{ lessonId: 'brihadaranyaka', why: 'Contrast concrete teaching analogies with the limits of positive description.' }, { lessonId: 'vedanta-schools', why: 'See why the same refrain has generated different commentarial conclusions.' }],
    sourceLinks: [{ label: 'Chāndogya 6.13: historical translation', url: 'https://sacred-texts.com/hin/sbe01/sbe01131.htm' }, { label: 'Chāndogya Sanskrit', url: 'https://sanskritdocuments.org/doc_upanishhat/chhaandogya.html' }],
    excerpt: excerpt('Chāndogya 6.8.7 · recurring refrain', 'तत्त्वमसि श्वेतकेतो ।', 'tat tvam asi śvetaketo', 'You are that, Śvetaketu.', 'https://sanskritdocuments.org/doc_upanishhat/chhaandogya.html', 'The refrain returns through chapter 6. Tat + tvam + asi are joined in the written Sanskrit. This straightforward course rendering does not decide the disputed metaphysical relation; later Vedānta explanations must be read as interpretations.', [word('तत्', 'tat', 'that', 'Neuter pronoun referring back to the reality under discussion.'), word('त्वम्', 'tvam', 'you', 'Second-person singular nominative pronoun.'), word('असि', 'asi', 'are', 'Second-person singular present of √as, to be.'), word('श्वेतकेतो', 'śvetaketo', 'O Śvetaketu', 'Vocative singular: the teacher directly addresses the student.')]),
  },
  brihadaranyaka: {
    opening: 'Before leaving household life, Yājñavalkya offers to divide his property. Maitreyī asks whether wealth could make her immortal. Her question changes the conversation from managing possessions to asking what a worthwhile answer would be.',
    teaching: [
      { title: 'Let the question change the lesson', body: 'In 2.4, Maitreyī does not merely request a larger inheritance. She challenges what wealth can accomplish. Yājñavalkya grants its practical value but denies that it supplies immortality. The dialogue then turns toward self, love, and knowing. Its dramatic setting matters: philosophy begins when the offered solution does not meet the learner’s real concern.' },
      { title: 'What can a description leave out?', body: 'The formula neti neti at 2.3.6 interrupts the assumption that a finite characterization exhausts reality. It is often translated “not this, not this.” That is not the same as “nothing exists.” Compare rejecting an inadequate description with denying its subject altogether. Later interpreters disagree about which positive account remains possible.' },
      { title: 'A collection of voices and arguments', body: 'Court debates include Gārgī’s questioning, while household dialogues have a different setting and pressure. The Maitreyī conversation occurs again at 4.5 with differences. This large, composite work rewards comparison: read speaker, setting, and argument before collecting its memorable formulas into a single system.' },
    ],
    example: { title: 'A description is not the whole person', scenario: 'Modern illustration: “She is a physician” is a true description, but it does not exhaust her relationships, history, or experience. Does saying “not only that” mean that she is not a physician or that she does not exist?', explanation: 'Neither. The example helps distinguish limiting a description from abolishing its subject. It only introduces the logical move; neti neti’s inquiry concerns reality and self in a more demanding sense than a list of personal roles.' },
    visual: { title: 'Three questions, not three competing slogans', nodes: [{ label: 'What can wealth give?', detail: 'Maitreyī tests whether a practical good reaches the goal she seeks.' }, { label: 'What can words describe?', detail: 'Neti neti checks whether a finite description has been mistaken for an exhaustive one.' }, { label: 'How is the knower known?', detail: 'The dialogue turns toward what makes knowing possible, rather than another ordinary object.' }], caption: 'A thematic bridge between 2.3 and 2.4; these are distinct passages, not one continuous quotation.' },
    connections: [{ lessonId: 'kena', why: 'Return to the difficulty of treating the condition of knowing as one more object.' }, { lessonId: 'purusharthas', why: 'Compare wealth with other human goals without assuming money answers every question.' }],
    sourceLinks: [{ label: 'Bṛhadāraṇyaka Sanskrit', url: 'https://sanskritdocuments.org/doc_upanishhat/bribasic.html' }, { label: 'Maitreyī dialogue: historical translation', url: 'https://sacred-texts.com/hin/sbe15/sbe15061.htm' }],
    excerpt: excerpt('Bṛhadāraṇyaka 2.3.6 · brief formula', 'नेति नेति ।', 'neti neti', 'Not thus; not thus.', 'https://sanskritdocuments.org/doc_upanishhat/bribasic.html', 'This tiny excerpt is a formula within a larger account, not the whole passage. Each neti joins na + iti. “Not this, not this” is another common English rendering; neither rendering by itself settles later doctrinal debates.', [word('न', 'na', 'not', 'Indeclinable negation; a + i contracts to e in na + iti.'), word('इति', 'iti', 'thus; in this way', 'Indeclinable, often marking quoted or characterized speech.'), word('न', 'na', 'not', 'The negation is repeated.'), word('इति', 'iti', 'thus; in this way', 'Completes the repeated na + iti → neti.')]),
  },
  mandukya: {
    opening: 'You speak of yourself as awake, dreaming, and having slept. What changes across those experiences, and why do you call all of them yours? This twelve-mantra text builds its inquiry around that contrast and the syllable Oṃ.',
    teaching: [
      { title: 'Three familiar ways experience is organized', body: 'Mantras 3–6 describe waking as outward-oriented, dream as inward-oriented, and deep sleep as lacking the ordinary differentiated experiences of the first two. Do not start by forcing these into brain-wave categories. The text is examining self and experience through its own philosophical and contemplative vocabulary.' },
      { title: 'Why the fourth is difficult', body: 'Mantra 7 refuses to describe the fourth simply as outward knowing, inward knowing, both, or mere absence of knowing. The purpose is to stop the reader from treating it as another familiar item on the list. Naming it “fourth” gives a point of comparison, but does not make it just a fourth episode in the nightly sleep cycle.' },
      { title: 'A syllable becomes a teaching map', body: 'Mantras 8–12 relate A, U, and M to the first three aspects and amātra, without a syllabic measure or part, to the fourth. This is an aid for contemplation, not proof obtained by making a particular sound. Gauḍapāda’s extensive Kārikā is later philosophical development, even when an edition prints it beside the short Upaniṣad.' },
    ],
    example: { title: 'A memory of dream', scenario: 'Modern illustration: you dream that you are walking through a city, then wake in your room. The city was not present as an ordinary waking location, yet the dream was experienced. What distinction does this make visible?', explanation: 'The experienced content and its mode can change. That helps introduce waking versus dream. It does not establish that the entire waking world is a private dream, nor does one remembered dream prove the fourth. Those stronger claims require separate arguments.' },
    visual: { title: 'Four aspects, not a sleep timetable', nodes: [{ label: 'Waking · A', detail: 'Experience directed toward outward objects.' }, { label: 'Dream · U', detail: 'Experience described as inwardly knowing.' }, { label: 'Deep sleep · M', detail: 'Ordinary differentiated dreaming and desire are absent in the text’s description.' }, { label: 'The fourth', detail: 'Not exhausted by those descriptions; the measureless teaching of mantra 12 is coordinated with it.' }], caption: 'The order follows the text’s exposition. Do not read the final card as another clinical sleep stage.' },
    connections: [{ lessonId: 'prashna', why: 'Compare another Atharvavedic account of sleep, Oṃ, and the person.' }, { lessonId: 'vedanta-schools', why: 'Keep the short root text distinct from later philosophical systems.' }],
    sourceLinks: [{ label: 'Māṇḍūkya Sanskrit', url: portal('mandukyopanishad') }, { label: 'GRETIL: Gauḍapāda’s later Kārikā', url: 'https://gretil.sub.uni-goettingen.de/gretil/1_sanskr/1_veda/4_upa/gmandk_u.htm' }],
    excerpt: excerpt('Māṇḍūkya 2 · middle statement', 'अयमात्मा ब्रह्म ।', 'ayam ātmā brahma', 'This self is brahman.', portal('mandukyopanishad'), 'A sentence excerpted from mantra 2. The present-tense “is” is supplied in English. The following statement in the Sanskrit describes this self as four-footed or fourfold; the rest of the work explains that framework.', [word('अयम्', 'ayam', 'this', 'Masculine nominative singular demonstrative, agreeing with ātmā.'), word('आत्मा', 'ātmā', 'self', 'Nominative singular of ātman; joined after ayam in the source.'), word('ब्रह्म', 'brahma', 'brahman; ultimate reality', 'Neuter nominative singular of brahman, not the masculine creator Brahmā.')]),
  },
  aitareya: {
    opening: 'Seeing, remembering, and deciding feel different. This text asks what allows us to call them all knowing. It reaches that question through an account of worlds, bodily faculties, and the life that depends on food.',
    teaching: [
      { title: 'Begin with embodiment', body: 'The first chapter narrates the emergence of worlds and a person’s faculties. Speech, sight, hearing, and other powers are situated within a larger cosmos. Food matters because faculties do not operate in an unsupported vacuum. Read the sequence as a textual account of dependence and embodiment, not as a modern biological explanation.' },
      { title: 'Ask which self is being investigated', body: 'Chapter 3 asks what is meant by the self under discussion. Instead of pointing immediately to an object, it catalogs activities such as seeing, hearing, understanding, memory, intention, and desire. Prajñāna gathers these modes of knowing into the inquiry. Translating it as consciousness can help, provided modern assumptions are not smuggled in unnoticed.' },
      { title: 'Read the great saying in its paragraph', body: 'Prajñānam brahma becomes a major formula in later Vedānta. In the source it follows the attention to knowing and the living world. Read both the catalogue and the conclusion: repeating the formula cannot substitute for explaining what prajñāna means or how the text reaches its claim.' },
    ],
    example: { title: 'Remembering a mango', scenario: 'Modern illustration: seeing a mango, remembering its taste, and deciding to buy it are different activities. A student says the passage is only about eyesight. What part of its argument would that leave out?', explanation: 'It would omit memory, decision, and the broader range of knowing collected under prajñāna. The exercise clarifies the word’s scope in the passage, without claiming that the text supplies a modern neurological model.' },
    visual: { title: 'From a world to the question of knowing', nodes: [{ label: 'World and body', detail: 'Chapter 1 situates faculties, food, and embodied life.' }, { label: 'Many activities', detail: 'Chapter 3 collects seeing, remembering, understanding, willing, and more.' }, { label: 'Prajñāna', detail: 'The inquiry names their knowing character and relates it to brahman.' }], caption: 'A thematic route through the work, not a timeline of biological evolution.' },
    connections: [{ lessonId: 'kaushitaki', why: 'Compare another Ṛgvedic teaching on the relation between life and knowing.' }, { lessonId: 'taittiriya', why: 'Notice how food and embodiment remain part of philosophical inquiry.' }],
    sourceLinks: [{ label: 'TITUS: Aitareya chapter 3', url: 'https://titus.fkidg1.uni-frankfurt.de/texte/etcd/ind/aind/ved/rv/upanisad/aitup/aitup003.htm' }, { label: 'Vedic Heritage: Aitareya', url: portal('aitareyopanishad') }],
    excerpt: excerpt('Aitareya 3.1.3 · concluding formula', 'प्रज्ञानं ब्रह्म ।', 'prajñānaṃ brahma', 'Knowing awareness is brahman.', 'https://titus.fkidg1.uni-frankfurt.de/texte/etcd/ind/aind/ved/rv/upanisad/aitup/aitup003.htm', 'This is a small part of a longer paragraph; the preceding catalogue supplies context. The linked TITUS edition displays Devanagari and split-word forms. This course adds a beginner-friendly IAST transliteration.', [word('प्रज्ञानम्', 'prajñānam', 'knowing awareness; cognition', 'Neuter nominative singular; final m becomes anusvāra ṃ before b.'), word('ब्रह्म', 'brahma', 'brahman; ultimate reality', 'Neuter nominative singular. The English linking verb is understood, not a separate Sanskrit word.')]),
  },
  kaushitaki: {
    opening: 'When someone says “I was looking but did not notice,” an eye’s activity and a person’s knowing are being distinguished. Kauṣītaki asks us to consider the living knower rather than treat each faculty as an independent self.',
    teaching: [
      { title: 'Indra gives an unexpected teaching', body: 'In chapter 3, Pratardana encounters Indra, who redirects the exchange toward knowledge of vital life and awareness. A dramatic divine speaker is not a neutral textbook narrator. Track the dialogue’s goal before treating isolated sentences about Indra or prāṇa as universal definitions.' },
      { title: 'A capacity is not the whole person', body: 'The text tests what happens when individual faculties are absent and places them within the unity of prāṇa and prajñā. Vital life here is more than air moving in and out. The argument concerns the coordinated living person; it should not be used to rank people’s worth by their sensory capacities.' },
      { title: 'Turn from the known to the knower', body: 'At 3.8, the instruction redirects attention from speech to the speaker, sights to the one who knows sights, and similarly through other capacities. This does not make speech useless. It shifts the question from what is presented to the living awareness through which it is known.' },
    ],
    example: { title: 'Words heard without attention', scenario: 'Modern illustration: you hear a sentence while distracted, then ask the speaker to repeat it. What difference is there between a sound reaching you and your understanding the sentence?', explanation: 'The example separates sensory occurrence from attentive knowing. It introduces the chapter’s concern with coordinated faculties, but it does not identify prāṇa with a particular brain process or claim that understanding can be measured by breathing alone.' },
    visual: { title: 'One event, three questions', nodes: [{ label: 'The sound', detail: 'What is heard? This is the presented content.' }, { label: 'The faculty', detail: 'How does hearing participate? A capacity contributes to the event.' }, { label: 'The living knower', detail: 'Who hears and understands? The text redirects inquiry toward prāṇa and prajñā.' }], caption: 'These are analytical perspectives on one event, not independently functioning miniature persons.' },
    connections: [{ lessonId: 'kena', why: 'Compare “the ear of the ear” with this turn toward the knower.' }, { lessonId: 'prashna', why: 'Compare the contest of faculties and the coordinating role of prāṇa.' }],
    sourceLinks: [{ label: 'Kauṣītaki Sanskrit', url: 'https://sanskritdocuments.org/doc_upanishhat/kaushhiitaki.html' }, { label: 'TITUS: Kauṣītaki chapter 3', url: 'https://titus.fkidg1.uni-frankfurt.de/texte/etcs/ind/aind/ved/rv/upanisad/kausup/kausu003.htm' }],
    excerpt: excerpt('Kauṣītaki 3.8 · opening instruction', 'न वाचं विजिज्ञासीत वक्तारं विद्यात् ।', 'na vācaṃ vijijñāsīta vaktāraṃ vidyāt', 'One should not seek to understand speech [alone]; one should know the speaker.', 'https://sanskritdocuments.org/doc_upanishhat/kaushhiitaki.html', 'Excerpt ends before the next parallel instruction. “Alone” is an explanatory addition, shown in brackets. The two verbs are optatives: instructions about how one should inquire, not commands to stop communicating.', [word('न', 'na', 'not', 'Indeclinable negation.'), word('वाचम्', 'vācam', 'speech', 'Accusative singular of vāc, object; final m appears as ṃ before v.'), word('विजिज्ञासीत', 'vijijñāsīta', 'one should seek to understand', 'Third-person singular middle optative of the desiderative of vi-√jñā.'), word('वक्तारम्', 'vaktāram', 'the speaker', 'Accusative singular of vaktṛ, an agent noun; m becomes ṃ before v.'), word('विद्यात्', 'vidyāt', 'one should know', 'Third-person singular active optative of √vid.')]),
  },
  prashna: {
    opening: 'Six students bring six questions. Before answering, Pippalāda asks them to prepare for a year. This is a course about learning to ask well as much as it is a collection of answers.',
    teaching: [
      { title: 'Preparation does not cancel questioning', body: 'At 1.1–2 the students approach with a serious wish to know brahman. Pippalāda asks for discipline, studently conduct, and trustful commitment, then says he will answer if he knows. Preparation is part of inquiry. The teacher’s qualification matters too: it is not a declaration of automatic omniscience.' },
      { title: 'Why the faculties tell a story', body: 'Question 2 stages a contest among powers supporting the person. When prāṇa appears to withdraw, the others follow, like bees following their leader. The story shifts attention from each faculty’s boast to its dependence. Its following praise extends the analogy into Vedic and cosmic relationships rather than giving a physiological mechanism.' },
      { title: 'Follow the six-question arc', body: 'The questions move from origins to sustaining powers, prāṇa’s functions, sleep and dream, Oṃ, and the person with sixteen parts. In the final teaching, rivers losing separate names on reaching the sea become an image for the parts’ relation to the person. Each question enlarges the frame; they are not six interchangeable inspirational sayings.' },
    ],
    example: { title: 'Spokes and a hub', scenario: 'Textual image, 2.6: spokes depend on the hub of a chariot wheel. A student concludes that only the hub matters and the spokes have no role. Is that what dependence means?', explanation: 'No. The image explains how many functions are supported together. It does not make those functions nonexistent or unnecessary. Likewise, the praise of prāṇa situates the senses, ritual, and wider life in a coordinated account.' },
    visual: { title: 'Questions that widen the frame', nodes: [{ label: 'Origins · Q1', detail: 'Ask how living beings arise and how cosmic rhythms participate.' }, { label: 'Life and faculties · Q2–3', detail: 'Investigate what supports the person and how prāṇa functions.' }, { label: 'Experience and Oṃ · Q4–5', detail: 'Consider sleep, dream, and contemplative use of the syllable.' }, { label: 'Parts and person · Q6', detail: 'Ask where the sixteen parts originate and how their names and forms return.' }], caption: 'A reading itinerary through the six questions, not six stages of a modern breathing exercise.' },
    connections: [{ lessonId: 'mandukya', why: 'Compare the different treatment of sleep and Oṃ.' }, { lessonId: 'kaushitaki', why: 'Read another account of faculties within a living, knowing unity.' }],
    sourceLinks: [{ label: 'Praśna Sanskrit', url: portal('prashnopanishad') }, { label: 'Early Upaniṣads: UT Austin textual resource', url: 'https://sites.utexas.edu/sanskrit/resources/early-upanisads-olivelle-edition/' }],
    excerpt: excerpt('Praśna 2.6 · first half', 'अरा इव रथनाभौ प्राणे सर्वं प्रतिष्ठितम् ।', 'arā iva rathanābhau prāṇe sarvaṃ pratiṣṭhitam', 'Like spokes in a chariot’s hub, everything is established in vital life.', portal('prashnopanishad'), 'The second half names Vedic verses, formulas, chants, sacrifice, and powers of authority. This excerpt gives the image without substituting a modern physiology for prāṇa.', [word('अराः', 'arāḥ', 'spokes', 'Nominative masculine plural; visarga is lost before iva in this sandhi.'), word('इव', 'iva', 'like; as', 'Indeclinable marker of comparison.'), word('रथनाभौ', 'rathanābhau', 'in a chariot’s hub', 'Locative singular compound: ratha, chariot, + nābhi, hub.'), word('प्राणे', 'prāṇe', 'in vital life', 'Locative singular of prāṇa.'), word('सर्वम्', 'sarvam', 'everything', 'Neuter nominative singular; final m becomes ṃ before p.'), word('प्रतिष्ठितम्', 'pratiṣṭhitam', 'established; supported', 'Past passive participle of prati-√sthā, agreeing with sarvam.')]),
  },
  shvetashvatara: {
    opening: 'Is the world explained by time, nature, necessity, chance, or agency? Śvetāśvatara begins with this causal puzzle and brings contemplative discipline into a strongly theistic inquiry.',
    teaching: [
      { title: 'Do not mistake a list for an answer', body: 'At 1.1–3, possible causes are considered rather than merely listed as things to believe. The text asks whether any proposed cause is sufficient and turns toward a divine power disclosed through contemplation. Read the movement from question to proposed insight; its theological conclusion is part of its argument, not a neutral modern scientific finding.' },
      { title: 'Practice has a textual setting', body: 'Chapter 2 describes steadiness, breath, collected senses, and a suitable setting as parts of inquiry. This is one historically important account of yoga, not the finished eight-limbed system of a later treatise. Here we study what the text says; the lesson is not a prescription for breath retention or a promise of medical benefits.' },
      { title: 'A divine presence within many beings', body: 'The work names Rudra and speaks of a supreme deva; 6.11 describes the one divine presence concealed in all beings. These are important to later Śaiva and Vedānta readers. Do not erase the theistic voice by translating everything into impersonal psychology, or assume every later Śaiva doctrine is already fully present.' },
    ],
    example: { title: 'A cause versus a complete explanation', scenario: 'Modern illustration: a seed grows when time passes. Does “time passed” fully explain its growth, or have you omitted conditions such as seed, soil, and water? How does that help you understand the opening question?', explanation: 'It shows why naming one candidate need not supply a sufficient explanation. The Upaniṣad pursues a much larger causal and theological inquiry; the seed illustration helps frame the question but cannot independently establish its answer.' },
    visual: { title: 'Inquiry, discipline, and theological language', nodes: [{ label: 'Test proposed causes', detail: 'The opening refuses to accept a candidate merely because it has been named.' }, { label: 'Gather attention', detail: 'Contemplative discipline is part of how the work approaches knowing.' }, { label: 'Name the divine', detail: 'Rudra and the one deva give the work a distinct theistic voice.' }], caption: 'Three connected strands of this Upaniṣad; not a claim that all Upaniṣads have the same theology.' },
    connections: [{ lessonId: 'shaiva-worlds', why: 'Follow later Śaiva traditions without collapsing them into this earlier work.' }, { lessonId: 'classical-yoga', why: 'Compare yoga vocabularies and preserve the differences between systems.' }],
    sourceLinks: [{ label: 'Śvetāśvatara Sanskrit', url: 'https://sanskritdocuments.org/doc_upanishhat/shveta.html' }, { label: 'Śvetāśvatara: Vedic Heritage orientation', url: portal('shwetashwataropanishad') }],
    excerpt: excerpt('Śvetāśvatara 6.11 · opening line', 'एको देवः सर्वभूतेषु गूढः ।', 'eko devaḥ sarvabhūteṣu gūḍhaḥ', 'The one divine being is hidden in all beings.', 'https://sanskritdocuments.org/doc_upanishhat/shveta.html', 'This is the opening of a longer verse describing the inner presence, witness, and knower. Its theistic language should remain visible even when compared with nondual interpretations.', [word('एकः', 'ekaḥ', 'one', 'Masculine nominative singular; ekaḥ + devaḥ → eko devaḥ.'), word('देवः', 'devaḥ', 'divine being; deity', 'Masculine nominative singular.'), word('सर्वभूतेषु', 'sarvabhūteṣu', 'in all beings', 'Locative plural compound of sarva, all, and bhūta, being.'), word('गूढः', 'gūḍhaḥ', 'hidden; concealed', 'Masculine nominative singular participle agreeing with devaḥ.')]),
  },
  maitri: {
    opening: 'A king has power but cannot command time to stop. Bṛhadratha’s confrontation with decay opens a layered work that investigates self, mind, time, and contemplative practice.',
    teaching: [
      { title: 'What power cannot secure', body: 'In the opening, Bṛhadratha reflects on bodily change and the impermanence even of eminent beings. Renunciation follows a question about what lasts, not simply disappointment at having too little. Notice what changes when the problem is not obtaining a desirable thing but understanding why desirable things cannot remain secure.' },
      { title: 'Mind belongs to both sides of the problem', body: 'In the received sixth chapter’s teaching around 6.34, mind is associated with bondage and release according to its attachment or freedom from objects. This is a contemplative claim in a larger philosophical setting. It is not a claim that people cause every hardship by thinking incorrectly, nor a substitute for help with illness or material injustice.' },
      { title: 'Sixfold yoga is not an abbreviated eightfold list', body: 'At 6.18, breath regulation, withdrawal, meditation, fixed attention, inquiry, and absorption form a sixfold account. Compare it with other texts without erasing the different list or order. The received work contains layers and supplements: a teaching in chapter 6 should not automatically be dated to the opening royal dialogue.' },
    ],
    example: { title: 'Losing an argument twice', scenario: 'Modern illustration: an argument ends, but a person keeps replaying it and imagining revenge. What is the difference between the original event and the attention that continues to sustain it?', explanation: 'The event and the continuing attachment are distinguishable. This can introduce the text’s concern with mind, but it does not establish that changing attention resolves every external wrong. Philosophical reflection and practical responsibility need not exclude each other.' },
    visual: { title: 'Keep three layers of the reading separate', nodes: [{ label: 'Royal dialogue', detail: 'Bṛhadratha’s mortality question motivates a search for self-knowledge.' }, { label: 'Received supplements', detail: 'Later portions develop mind, time, Oṃ, and sixfold yoga in a layered textual setting.' }, { label: 'Commentarial reception', detail: 'Much later teachers interpret the transmitted text; their explanations are not automatically its original wording.' }], caption: 'A source map, not an exact dating of every passage. Editions and internal numbering can differ.' },
    connections: [{ lessonId: 'katha', why: 'Compare Naciketas and Bṛhadratha: mortality changes what each learner asks for.' }, { lessonId: 'classical-yoga', why: 'Compare sixfold and eight-limbed accounts without merging them.' }],
    sourceLinks: [{ label: 'Maitrī: Sanskrit, with variant texts', url: 'https://sanskritdocuments.org/doc_upanishhat/maitri.html' }, { label: 'Maitrāyaṇī: Vedic Heritage orientation', url: portal('maitrayani-upanishad') }],
    excerpt: excerpt('Maitrī 6.34 · verse 11, first half (received long text)', 'मन एव मनुष्याणां कारणं बन्धमोक्षयोः ।', 'mana eva manuṣyāṇāṃ kāraṇaṃ bandhamokṣayoḥ', 'Mind itself is, for human beings, a cause of bondage and release.', 'https://sanskritdocuments.org/doc_upanishhat/maitri.html', 'A half-verse, also transmitted in related Upaniṣadic material. The linked page contains more than one received version: this excerpt follows the spelling manuṣyāṇām in the earlier displayed version; the long-text section prints manuṣyāṇam. The following half contrasts attachment with freedom from attachment; this is not a claim that thoughts cause every illness or hardship.', [word('मनः', 'manaḥ', 'mind', 'Neuter nominative singular of manas; visarga is lost before eva here.'), word('एव', 'eva', 'itself; indeed', 'Indeclinable emphasis.'), word('मनुष्याणाम्', 'manuṣyāṇām', 'of human beings; for people', 'Genitive plural; final m becomes ṃ before k.'), word('कारणम्', 'kāraṇam', 'cause', 'Neuter nominative singular; final m becomes ṃ before b.'), word('बन्धमोक्षयोः', 'bandhamokṣayoḥ', 'of bondage and release', 'Genitive dual compound: bandha + mokṣa.')]),
  },
}
